# set base image (host OS)
FROM ...

# set the working directory in the container
WORKDIR ...

# copy the dependencies file to the working directory
COPY ...

# install dependencies
RUN ...

# Copy code to the working directory
COPY ...

# command to run on container start
ENTRYPOINT ...
